# Generated by Django 3.0.3 on 2020-04-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
